const statsWorlds2011 = [
    { nombre_campeon: 'Nunu', victorias: 12, derrotas: 6 },
    { nombre_campeon: 'Alistar', victorias: 8, derrotas: 5 },
    { nombre_campeon: 'Rumble', victorias: 2, derrotas: 0 },
    { nombre_campeon: 'Vladimir', victorias: 3, derrotas: 5 },
    { nombre_campeon: 'Twisted Fate', victorias: 2, derrotas: 2 },
    { nombre_campeon: 'Vayne', victorias: 4, derrotas: 4 },
    { nombre_campeon: 'Jarvan IV', victorias: 8, derrotas: 5 },
    { nombre_campeon: 'Corki', victorias: 8, derrotas: 7 },
    { nombre_campeon: 'Nidalee', victorias: 3, derrotas: 1 },
    { nombre_campeon: 'Janna', victorias: 10, derrotas: 8 },
    { nombre_campeon: 'Ashe', victorias: 13, derrotas: 4 },
    { nombre_campeon: 'Sona', victorias: 9, derrotas: 6 },
    { nombre_campeon: 'Amumu', victorias: 3, derrotas: 7 },
    { nombre_campeon: 'Malzahar', victorias: 9, derrotas: 7 },
    { nombre_campeon: 'Warwick', victorias: 6, derrotas: 5 },
    { nombre_campeon: 'Anivia', victorias: 5, derrotas: 4 },
    { nombre_campeon: 'Taric', victorias: 3, derrotas: 7 },
    { nombre_campeon: 'Annie', victorias: 4, derrotas: 4 },
    { nombre_campeon: 'Karthus', victorias: 2, derrotas: 4 },
    { nombre_campeon: 'Soraka', victorias: 2, derrotas: 5 },
    { nombre_campeon: 'Miss Fortune', victorias: 2, derrotas: 6 },
    { nombre_campeon: 'Brand', victorias: 3, derrotas: 5 },
    { nombre_campeon: 'Zilean', victorias: 1, derrotas: 1 },
    { nombre_campeon: 'Nocturne', victorias: 2, derrotas: 2 },
    { nombre_campeon: 'Irelia', victorias: 1, derrotas: 3 },
    { nombre_campeon: 'Gragas', victorias: 3, derrotas: 1 },
    { nombre_campeon: 'Akali', victorias: 1, derrotas: 0 },
    { nombre_campeon: 'Singed', victorias: 2, derrotas: 2 },
    { nombre_campeon: 'Swain', victorias: 2, derrotas: 3 },
    { nombre_campeon: 'Caitlyn', victorias: 0, derrotas: 4 },
    { nombre_campeon: 'Trundle', victorias: 0, derrotas: 3 },
    { nombre_campeon: 'Tristana', victorias: 1, derrotas: 2 },
    { nombre_campeon: 'Mordekaiser', victorias: 1, derrotas: 0 },
    { nombre_campeon: "Cho'Gath", victorias: 1, derrotas: 2 }, // Nota: Apóstrofe escapado con \
    { nombre_campeon: 'Teemo', victorias: 1, derrotas: 1 },
    { nombre_campeon: 'Lee Sin', victorias: 1, derrotas: 1 },
    { nombre_campeon: 'Urgot', victorias: 0, derrotas: 1 },
    { nombre_campeon: 'Sion', victorias: 1, derrotas: 0 },
    { nombre_campeon: 'Rammus', victorias: 0, derrotas: 1 },
    { nombre_campeon: 'Poppy', victorias: 0, derrotas: 1 },
    { nombre_campeon: 'Lux', victorias: 0, derrotas: 1 },
    { nombre_campeon: 'Kassadin', victorias: 0, derrotas: 1 },
    { nombre_campeon: 'Garen', victorias: 0, derrotas: 1 },
    { nombre_campeon: 'Gangplank', victorias: 1, derrotas: 0 },
    { nombre_campeon: "Dr. Mundo", victorias: 0, derrotas: 1 },
    { nombre_campeon: 'Blitzcrank', victorias: 0, derrotas: 1 }
  ];
  
  // Puedes añadir un console.log para verificar:
  // console.log(statsDelTorneo);