// stats_torneo_ejemplo.js
const statsTorneoEjemplo = [
  { nombre_campeon: "Aatrox",       victorias: 1, derrotas: 1 },
  { nombre_campeon: "Ahri",         victorias: 5, derrotas: 2 },
  { nombre_campeon: "Akali",        victorias: 3, derrotas: 3 },
  { nombre_campeon: "Akshan",       victorias: 0, derrotas: 1 }, // Ejemplo con 0 victorias
  { nombre_campeon: "Alistar",      victorias: 4, derrotas: 6 },
  { nombre_campeon: "Nunu",         victorias: 2, derrotas: 2 }, // Asegúrate que el nombre coincida EXACTO con champs.json
  { nombre_campeon: "Rumble",       victorias: 6, derrotas: 1 },
  { nombre_campeon: "Vladimir",     victorias: 1, derrotas: 4 },
  { nombre_campeon: "Twisted Fate", victorias: 3, derrotas: 0 }, // Ejemplo con 0 derrotas
  { nombre_campeon: "Corki",        victorias: 7, derrotas: 3 },
  { nombre_campeon: "Jarvan IV",    victorias: 4, derrotas: 4 },
  { nombre_campeon: "Vayne",        victorias: 2, derrotas: 5 },
  { nombre_campeon: "Janna",        victorias: 8, derrotas: 2 },
  { nombre_campeon: "Ashe",         victorias: 3, derrotas: 3 },
  { nombre_campeon: "Nidalee",      victorias: 1, derrotas: 2 },
  { nombre_campeon: "Sona",         victorias: 6, derrotas: 4 },
  { nombre_campeon: "Amumu",        victorias: 2, derrotas: 1 },
  { nombre_campeon: "Malzahar",     victorias: 0, derrotas: 0 }, // Ejemplo sin partidas
  { nombre_campeon: "Warwick",      victorias: 1, derrotas: 3 },
  { nombre_campeon: "Anivia",       victorias: 5, derrotas: 1 },
  { nombre_campeon: "Taric",        victorias: 2, derrotas: 2 },
  { nombre_campeon: "Annie",        victorias: 4, derrotas: 0 },
  { nombre_campeon: "Karthus",      victorias: 3, derrotas: 5 },
  { nombre_campeon: "Brand",        victorias: 1, derrotas: 1 },
  { nombre_campeon: "Miss Fortune", victorias: 2, derrotas: 6 },
  { nombre_campeon: "Soraka",       victorias: 7, derrotas: 3 },
  { nombre_campeon: "Gragas",       victorias: 4, derrotas: 2 },
  { nombre_campeon: "Cho'Gath",     victorias: 1, derrotas: 4 },
  { nombre_campeon: "Garen",        victorias: 6, derrotas: 1 },
  { nombre_campeon: "Nocturne",     victorias: 3, derrotas: 3 },
  { nombre_campeon: "Irelia",       victorias: 5, derrotas: 2 },
  { nombre_campeon: "Zilean",       victorias: 0, derrotas: 2 },
  { nombre_campeon: "Singed",       victorias: 2, derrotas: 1 },
  { nombre_campeon: "Swain",        victorias: 4, derrotas: 4 },
  { nombre_campeon: "Caitlyn",      victorias: 7, derrotas: 0 },
  { nombre_campeon: "Tristana",     victorias: 3, derrotas: 5 },
  { nombre_campeon: "Trundle",      victorias: 2, derrotas: 2 },
  { nombre_campeon: "Mordekaiser",  victorias: 1, derrotas: 3 },
  { nombre_campeon: "Lee Sin",      victorias: 9, derrotas: 1 },
  { nombre_campeon: "Teemo",        victorias: 0, derrotas: 4 },
  { nombre_campeon: "Gangplank",    victorias: 3, derrotas: 2 },
  { nombre_campeon: "Sion",         victorias: 1, derrotas: 5 },
  { nombre_campeon: "Blitzcrank",   victorias: 2, derrotas: 3 },
  { nombre_campeon: "Dr. Mundo",    victorias: 4, derrotas: 1 },
  { nombre_campeon: "Kassadin",     victorias: 1, derrotas: 6 },
  { nombre_campeon: "Lux",          victorias: 5, derrotas: 0 },
  { nombre_campeon: "Poppy",        victorias: 2, derrotas: 4 },
  { nombre_campeon: "Rammus",       victorias: 3, derrotas: 3 },
  { nombre_campeon: "Urgot",        victorias: 0, derrotas: 1 }
];